name: Lint GitHub Actions files

on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-github-actions-files:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: reviewdog/action-actionlint@abd537417cf4991e1ba8e21a67b1119f4f53b8e0 # v1.64.1
        with:
          tool_name: actionlint
          reporter: github-pr-review
          fail_on_error: true
