name: Lint GitHub Actions files

on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-github-actions-files:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          tool_name: actionlint
          reporter: github-pr-review
          fail_on_error: true
