name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x

    steps:
      - uses: actions/checkout@v4
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: npm install
        run: npm ci --no-audit --no-fund

      - name: validate renovate config
        run: npx --package renovate -c 'renovate-config-validator'

      - name: lint
        run: npm run lint
